version: '3.8'

services:
  btc-price-alert:
    build: .
    container_name: btc-price-alert
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - ENVIRONMENT=production
      - DATABASE_PATH=/app/data/alerts.db
      - CHECK_INTERVAL=30s
      - ENABLE_DESKTOP_NOTIFICATIONS=false  # Disabled in container
      - ENABLE_EMAIL_NOTIFICATIONS=true
      # Email configuration (override with your values)
      - SMTP_HOST=${SMTP_HOST:-smtp.gmail.com}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - FROM_EMAIL=${FROM_EMAIL}
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: btc-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro  # Mount SSL certificates if available
    depends_on:
      - btc-price-alert
    restart: unless-stopped
    profiles:
      - proxy  # Only start with: docker-compose --profile proxy up

volumes:
  data:
    driver: local 